// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bljjkzgswgeqswuuryvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsampremdzd2dlcXN3dXVyeXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjQyOTIsImV4cCI6MjA1OTg0MDI5Mn0.YKfesJP85Hhgo0Jmfsm96vnJooM8wO6FcrchZj5wL1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);